### ISSUE TITLE
Does the redismod container need to use append only?

### ISSUE THREAD

**Issue by simonprickett** [redis/redis-om-python#72]
The Redis server in the redismod container used for runnign tests has an append only file configured.  Is this needed?

If not, then this:

```yaml
services:
  redis:
    image: "redislabs/redismod:edge"
    entrypoint: ["redis-server", "--appendonly", "yes", "--loadmodule", "/usr/lib/redis/modules/rejson.so", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./data:/data
```

could be updated / simplified to:

```yaml
services:
  redis:
    image: "redislabs/redismod:edge"
    entrypoint: ["redis-server", "--loadmodule", "/usr/lib/redis/modules/rejson.so", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
    restart: always
    ports:
      - "6380:6379"
```
